### ISSUE TITLE
Imported VM created in 86Box Manager 1.72 gives Access violation when trying to go to settings in WinBox

### ISSUE THREAD

**Issue by tomrune** [laciba96/WinBox-Reloaded#10] opened 2021-06-13 13:05 UTC
![image](https://user-images.githubusercontent.com/14229801/121808442-cfc64d00-cc58-11eb-889a-39f0397333a6.png)

**Comment by laciba96** [comment] 2021-06-13 17:16
I have not met such a message before, and I don't know how can I reproduce this message. Does it happens with every VM created by 86Box Manager 1.72, or there were just this one? When does this error occurs (e.g. at the import dialog, after the import dialog closed, after it appeared in the list and you clicked it, ...)? 

I want to fix this error but I probably need more information about the reproduction of this bug.

**Comment by laciba96** [comment] 2021-06-15 16:03
I plan a complete revisit, and refactor of the program, and I want to rewrite many parts. There are many random bugs right now so, and since this is also some kind of random bug, such a grand update hopefully also fix this. This could take months, so for now I close this thread.

**Closed by laciba96** 2021-06-15 16:03 UTC
Labels: bug
