### ISSUE TITLE
[BUG] Program crashes after deleting VM and it's files.

### ISSUE THREAD

**Issue by explorerdotexe** [laciba96/WinBox-Reloaded#11] opened 2021-06-13 13:06 UTC
This issue occurs after deleting an existing VM, along with all of it's files. This issue doesn't occur when deleting only the machine itself, but not it's files.

**How to reproduce:**
1. Create a new VM inside WinBox.
2. Right-click and select "Delete Virtual Machine..."
3. Click "yes" to the dialogue box asking you if you want to delete all of it's files or just the VM itself.

**Screenshots:**
![image](https://user-images.githubusercontent.com/74715154/121808366-634b4e00-cc58-11eb-8482-09348a59faea.png)
The dialogue box where the crash can occur.

**Info:**
OS: Windows 10 20H2 
WinBox version: v1.14
86Box version: Build 3013
Additional Info: None

**Comment by laciba96** [comment] 2021-06-13 17:07
Can you describe how the crash is occurs? The program simply closes, or there is an error message before it stops? Is it possible that WinBox don't have permission to delete the files e.g. it needs admin rights to delete, or similar? 

I've done the same exact steps on my Windows 10 20H2 Hungarian version, and for me it works fine. I want to find what can causes this bug, but it seems I need more information about this.

**Comment by explorerdotexe** [comment] 2021-06-14 18:49
> Can you describe how the crash is occurs? The program simply closes, or there is an error message before it stops? Is it possible that WinBox don't have permission to delete the files e.g. it needs admin rights to delete, or similar?
> 
> I've done the same exact steps on my Windows 10 20H2 Hungarian version, and for me it works fine. I want to find what can causes this bug, but it seems I need more information about this.

When i did it, the program deleted the vm then the window closed and i had to restart WinBox. However, after i restarted it the VM was deleted.

**Comment by laciba96** [comment] 2021-06-15 12:22
> I wasn't running the program as Administrator, maybe it needed that?

No, by default you don't need it. There are special occassions where it could help (like the VM is in C:\Program Files\ folder, etc.), but is more likely for me that it's some kind of mysterious bug in my program.

From the picture you sent me I can conclude that VM you deleted is a new template-based Generic PC/XT compatible. 
Did you changed anything in the creation wizard, or just clicked thru by the Next button, and the default values? 
Does this crash appears when you try to delete any kind of VM, or this just happens with specific VMs? 
Does it happens every time with these VMs, or this is a random bug, or it was just one-time crash?

Also thank you for the cooperation, and the detailed bug report because it helps me to find the cause of the problem.
These questions helps me to find, which part of the code can fail on your computer, and after I found why did the it crash, I hope I can fix it.

**Comment by explorerdotexe** [comment] 2021-06-15 12:39
> 
> 
> > I wasn't running the program as Administrator, maybe it needed that?
> 
> No, by default you don't need it. There are special occassions where it could help (like the VM is in C:\Program Files\ folder, etc.), but is more likely for me that it's some kind of mysterious bug in my program.
> 
> From the picture you sent me I concluded that the VM you deleted is a new template-based Generic PC/XT compatible.
> 
>     * Did you changed anything in the creation wizard, or just clicked thru by the Next button, and the default values?
> 
>     * Does this crash appears when you try to delete any kind of VM, or this just happens with specific VMs?
> 
>     * Does it happens every time when deleting VMs, or this is a random bug, or it was just one-time crash?
> 
> 
> Also thank you for the cooperation, and the detailed bug report because it helps me to find the cause of the problem.
> These questions are for finding which part of my code can fail, and after I found why it failed, I hopefully can fix it.

Well i just retried it with a generic PC/XT compatible machine on it's default values, deleted the machine and it's files but now it didn't crash. I'm guessing it was a random bug that only happens sometimes.

**Comment by laciba96** [comment] 2021-06-15 15:59
Thank you for the test and the response.

Since after my program took a different direction in development, it seems to me, that it begins to fall apart in many scenarios. What I've seen on Discord, and in the recent bug reports, also suggest this to me. I guess the bug reported by you also fit in this set.

To solve this, I'm planning a complete refactor, and a complete revisit of the full code. I want to rewrite many parts of the programs, and I hope that this will solve many of the problems now appearing. Probably a step like this will eliminates these random bugs in the future.

Such a process will take a lot of time. Estimating my free time it could be months, but if I do it well, in the end there will be a much stable and faster program. Since I can't release a hotfix for this bug, for now I close this thread.

I hope that the most recent version is somewhat usable, while I finish the all of these stuff. If you don't need all the newest features of my program, you may check older versions (after v1.0), these was seemed more stable for me.

**Closed by laciba96** 2021-06-15 15:59 UTC
Labels: bug
